export const ADD_STUDENT = 'ADD_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const GET_ALL_STUDENT = 'GET_ALL_STUDENT';
export const GET_STUDENT_BY_ID = 'GET_STUDENT_BY_ID';
